export const FETCH_LYRICS_SUGGESTIONS = 'FETCH_LYRICS_SUGGESTIONS';
export const FETCH_LYRICS_SUGGESTIONS_SUCCESS =
  'FETCH_LYRICS_SUGGESTIONS_SUCCESS';
export const FETCH_LYRICS_SUGGESTIONS_ERROR = 'FETCH_LYRICS_SUGGESTIONS_ERROR';

export const FETCH_LYRICS = 'FETCH_LYRICS';
export const FETCH_LYRICS_SUCCESS = 'FETCH_LYRICS_SUCCESS';
export const FETCH_LYRICS_ERROR = 'FETCH_LYRICS_ERROR';
